version: "3"
services:

  chrome-1:
    image: selenium/node-chrome:4.0.0-beta-3-20210426
    volumes:
      - /dev/shm:/dev/shm
      - ./vnc.passwd:/home/seluser/.vnc/passwd
    environment:
      - SE_EVENT_BUS_HOST=selenium-1
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "5900:5900"
  selenium-1:
    image: selenium/hub:4.0.0-beta-3-20210426
    networks:
      default:
        aliases:
          - selenium-1
    #ports:
    #  - "4444:4444"
  impfbot-1:
    build:
      context: .
      dockerfile: Dockerfile
    image: impfbot
    restart: always
    volumes:
      - ./config.1.properties:/app/config.properties

  chrome-2:
    image: selenium/node-chrome:4.0.0-beta-3-20210426
    volumes:
      - /dev/shm:/dev/shm
      - ./vnc.passwd:/home/seluser/.vnc/passwd
    environment:
      - SE_EVENT_BUS_HOST=selenium-2
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "5901:5900"
  selenium-2:
    image: selenium/hub:4.0.0-beta-3-20210426
    networks:
      default:
        aliases:
          - selenium-2
    #ports:
    #  - "4444:4444"
  impfbot-2:
    build:
      context: .
      dockerfile: Dockerfile
    image: impfbot
    restart: always
    volumes:
      - ./config.2.properties:/app/config.properties


  chrome-3:
    image: selenium/node-chrome:4.0.0-beta-3-20210426
    volumes:
      - /dev/shm:/dev/shm
      - ./vnc.passwd:/home/seluser/.vnc/passwd
    environment:
      - SE_EVENT_BUS_HOST=selenium-3
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "5902:5900"
  selenium-3:
    image: selenium/hub:4.0.0-beta-3-20210426
    networks:
      default:
        aliases:
          - selenium-3
    #ports:
    #  - "4444:4444"
  impfbot-3:
    build:
      context: .
      dockerfile: Dockerfile
    image: impfbot
    restart: always
    volumes:
      - ./config.3.properties:/app/config.properties


  chrome-4:
    image: selenium/node-chrome:4.0.0-beta-3-20210426
    volumes:
      - /dev/shm:/dev/shm
      - ./vnc.passwd:/home/seluser/.vnc/passwd
    environment:
      - SE_EVENT_BUS_HOST=selenium-4
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "5903:5900"
  selenium-4:
    image: selenium/hub:4.0.0-beta-3-20210426
    networks:
      default:
        aliases:
          - selenium-4
    #ports:
    #  - "4444:4444"
  impfbot-4:
    build:
      context: .
      dockerfile: Dockerfile
    image: impfbot
    restart: always
    volumes:
      - ./config.4.properties:/app/config.properties
