version: "3"
services:

  chrome:
    image: selenium/node-chrome:4.0.0-beta-3-20210426
    volumes:
      - /dev/shm:/dev/shm
      - ./vnc.passwd:/home/seluser/.vnc/passwd
    environment:
      - SE_EVENT_BUS_HOST=selenium
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_SESSION_TIMEOUT=1800
    ports:
      - "5900:5900"
  selenium:
    image: selenium/hub:4.0.0-beta-3-20210426
    networks:
      default:
        aliases:
          - selenium
    #ports:
    #  - "4444:4444"
  impfbot:
    build:
      context: .
      dockerfile: Dockerfile
    image: impfbot
    restart: always
    volumes:
      - ./config.properties:/app/config.properties